#pragma once

#include "ImagineModels/RegularField.h"

#include "ImagineModels/Archimedes.h"
#include "ImagineModels/Fauvet.h"
#include "ImagineModels/HMR.h"
#include "ImagineModels/Han.h"
#include "ImagineModels/Helix.h"
#include "ImagineModels/JF12.h"
#include "ImagineModels/Jaffe.h"
#include "ImagineModels/KST24.h"
#include "ImagineModels/NE2025.h"
#include "ImagineModels/Pshirkov.h"
#include "ImagineModels/SVT22.h"
#include "ImagineModels/Stanev.h"
#include "ImagineModels/Sun.h"
#include "ImagineModels/TF17.h"
#include "ImagineModels/TT.h"
#include "ImagineModels/UF24.h"
#include "ImagineModels/Uniform.h"
#include "ImagineModels/WMAP.h"
#include "ImagineModels/XH24.h"

#include "ImagineModels/YMW16.h"
