name: ImagineModels C++ CI

on: [push]
 # push:
 #   branches: [ $main, ]
 # pull_request:
 #   branches: [ $main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: downloading and installing Catch2
      run: git clone https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install
    - name: downloading and installing fftw
      run: wget http://www.fftw.org/fftw-3.3.10.tar.gz && tar xzf fftw-3.3.10.tar.gz && cd fftw-3.3.10 && ./configure && make && sudo make install
    - name: downloading and installing Eigen3
      run: git clone https://gitlab.com/libeigen/eigen.git && cd eigen && mkdir build && cd build && cmake ..
    - name: downloading and installing autodiff
      run: git clone https://github.com/autodiff/autodiff.git && cd autodiff && mkdir .build && cd .build && cmake .. -DAUTODIFF_BUILD_PYTHON=OFF && cmake --build . --target install
    - name: load submodules
      run: git submodule update --init
    - name: cmake
      run: mkdir build && export MKPATH="${PWD}" && cd build && echo "${MKPATH}" && cmake "${MKPATH}"
    - name: make
      run: cd build && sudo make install
    - name: ctest
      run: cd build && ctest --output-on-failure --use-colour yes