name: ImagineModels C++ CI

on: [push]
 # push:
 #   branches: [ $main, ]
 # pull_request:
 #   branches: [ $main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: downloading and install fftw
      run: wget http://www.fftw.org/fftw-3.3.10.tar.gz && tar xzf fftw-3.3.10.tar.gz && cd fftw-3.3.10 && ./configure && make && sudo make install
    - name: load submodules
      run: git submodule update --init
    - name: debug
      run: ls && cd build && ls
    - name: cmake
      run: mkdir build && export MKPATH="${PWD}" && cd build && echo "${MKPATH}" && cmake "${MKPATH}"
    - name: make
      run: cd build && sudo make install
    - name: ctest
      run: cd build && ctest --output-on-failure --use-colour yes