name: ImagineModels C++ CI

on: [push]
 # push:
 #   branches: [ $main, ]
 # pull_request:
 #   branches: [ $main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: load submodules
      run: git submodule update --init
    - name: cmake
      run: mkdir build && export MKPATH="${PWD}" && cd build && echo "${MKPATH}" && cmake "${MKPATH}"
    - name: make
      run: cd build && make install
    - name: ctest
      run: ctest --output-on-failure --use-colour yes